MODEL:
  TYPE: vit
  NAME: cosiam_pretrain
  DROP_PATH_RATE: 0.1
  ENCODER:
    VIT:
      EMBED_DIM: 768
      DEPTH: 12
      NUM_HEADS: 12
      USE_APE: False
      USE_RPB: False
      USE_SHARED_RPB: True
      NUM_PROJECTION_LAYERS: 3
  DECODER:
    VIT:
      EMBED_DIM: 768
      DEPTH: 4
      NUM_HEADS: 12
      USE_APE: False
      USE_RPB: False
      USE_SHARED_RPB: False
DATA:
  IMG_SIZE: 416
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
TRAIN:
  BASE_MOMENTUM: 0.996
  EPOCHS: 800
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-4
  WARMUP_LR: 5e-7
  WEIGHT_DECAY: 0.05
  LR_SCHEDULER:
    NAME: 'multistep'
    GAMMA: 0.1
    MULTISTEPS: [700,]
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: cosiam_pretrain__vit_base__img448__800ep
