MODEL:
  TYPE: vit
  NAME: cosiam_pretrain
  DROP_PATH_RATE: 0.1
  ENCODER:
    VIT:
      EMBED_DIM: 512
      DEPTH: 12
      NUM_HEADS: 12
      USE_APE: True
      USE_RPB: False
      USE_SHARED_RPB: False
      NUM_PROJECTION_LAYERS: 3
  DECODER:
    VIT:
      EMBED_DIM: 512
      DEPTH: 3
      NUM_HEADS: 12
      USE_APE: False
      USE_RPB: False
      USE_SHARED_RPB: False
DATA:
  IMG_SIZE: 288
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
  NUM_BOXES: 250
TRAIN:
  BASE_MOMENTUM: 0.996
  EPOCHS: 50
  WARMUP_EPOCHS: 5
  BASE_LR: 1e-4
  WARMUP_LR: 5e-7
  WEIGHT_DECAY: 0.05
  LR_SCHEDULER:
    NAME: 'multistep'
    GAMMA: 0.1
    MULTISTEPS: [700,]
PRINT_FREQ: 10
SAVE_FREQ: 200
TAG: cosiam_pretrain__vit_base__img448__800ep
